# Generated by Django 2.0.2 on 2019-08-10 15:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sellerinfo',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sellerinfo',
            name='compane_site',
            field=models.URLField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='sellerinfo',
            name='company_name',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='sellerinfo',
            name='country',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='sellerinfo',
            name='dob',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='sellerinfo',
            name='info',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='sellerinfo',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True),
        ),
        migrations.AlterField(
            model_name='sellerinfo',
            name='photo',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='sellerinfo',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
