# Generated by Django 2.0.2 on 2019-08-11 21:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0002_sellpost'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentOutPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='')),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('size', models.PositiveSmallIntegerField()),
                ('price_per_month', models.PositiveIntegerField()),
                ('avilable_from', models.DateField(blank=True)),
                ('rent_type', models.CharField(choices=[('D', '1 day - 1 month'), ('M', '1 month - 1 year'), ('Y', '1 year or more')], default='M', max_length=1)),
                ('type', models.CharField(choices=[('H', 'House'), ('F', 'Flat'), ('R', 'Room'), ('O', 'Other')], default='F', max_length=1)),
                ('type_other', models.CharField(blank=True, max_length=50)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sellpost',
            name='price',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
