# Generated by Django 2.0.2 on 2019-08-13 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20190811_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='BuyPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('size_min', models.PositiveSmallIntegerField()),
                ('size_max', models.PositiveSmallIntegerField()),
                ('room_num', models.PositiveSmallIntegerField()),
                ('price_min', models.PositiveIntegerField()),
                ('price_max', models.PositiveIntegerField()),
                ('type', models.CharField(choices=[('H', 'House'), ('F', 'Flat'), ('R', 'Room'), ('O', 'Other')], default='F', max_length=1)),
                ('type_other', models.CharField(blank=True, max_length=50)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RentPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('district', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('size_min', models.PositiveSmallIntegerField()),
                ('size_max', models.PositiveSmallIntegerField()),
                ('room_num', models.PositiveSmallIntegerField()),
                ('price_per_month_min', models.PositiveIntegerField()),
                ('price_per_month_max', models.PositiveIntegerField()),
                ('check_in', models.DateField(blank=True)),
                ('check_out', models.DateField(blank=True)),
                ('rent_type', models.CharField(choices=[('D', '1 day - 1 month'), ('M', '1 month - 1 year'), ('Y', '1 year or more')], default='M', max_length=1)),
                ('type', models.CharField(choices=[('H', 'House'), ('F', 'Flat'), ('R', 'Room'), ('O', 'Other')], default='F', max_length=1)),
                ('type_other', models.CharField(blank=True, max_length=50)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
